const countryList1 = {
  AED: { countryCode: "AE", fullName: "United Arab Emirates Dirham" },
  AFN: { countryCode: "AF", fullName: "Afghan Afghani" },
  XCD: { countryCode: "AG", fullName: "East Caribbean Dollar" },
  ALL: { countryCode: "AL", fullName: "Albanian Lek" },
  AMD: { countryCode: "AM", fullName: "Armenian Dram" },
  ANG: { countryCode: "AN", fullName: "Netherlands Antillean Guilder" },
  AOA: { countryCode: "AO", fullName: "Angolan Kwanza" },
  AQD: { countryCode: "AQ", fullName: "Antarctic Dollar" },
  ARS: { countryCode: "AR", fullName: "Argentine Peso" },
  AUD: { countryCode: "AU", fullName: "Australian Dollar" },
  AZN: { countryCode: "AZ", fullName: "Azerbaijani Manat" },
  BAM: {
    countryCode: "BA",
    fullName: "Bosnia and Herzegovina Convertible Mark",
  },
  BBD: { countryCode: "BB", fullName: "Barbadian Dollar" },
  BDT: { countryCode: "BD", fullName: "Bangladeshi Taka" },
  XOF: { countryCode: "BE", fullName: "CFA Franc BCEAO" },
  BGN: { countryCode: "BG", fullName: "Bulgarian Lev" },
  BHD: { countryCode: "BH", fullName: "Bahraini Dinar" },
  BIF: { countryCode: "BI", fullName: "Burundian Franc" },
  BMD: { countryCode: "BM", fullName: "Bermudian Dollar" },
  BND: { countryCode: "BN", fullName: "Brunei Dollar" },
  BOB: { countryCode: "BO", fullName: "Bolivian Boliviano" },
  BRL: { countryCode: "BR", fullName: "Brazilian Real" },
  BSD: { countryCode: "BS", fullName: "Bahamian Dollar" },
  NOK: { countryCode: "BV", fullName: "Norwegian Krone" },
  BWP: { countryCode: "BW", fullName: "Botswana Pula" },
  BYR: { countryCode: "BY", fullName: "Belarusian Ruble" },
  BZD: { countryCode: "BZ", fullName: "Belize Dollar" },
  CAD: { countryCode: "CA", fullName: "Canadian Dollar" },
  CDF: { countryCode: "CD", fullName: "Congolese Franc" },
  XAF: { countryCode: "CF", fullName: "CFA Franc BEAC" },
  CHF: { countryCode: "CH", fullName: "Swiss Franc" },
  CLP: { countryCode: "CL", fullName: "Chilean Peso" },
  CNY: { countryCode: "CN", fullName: "Chinese Yuan" },
  COP: { countryCode: "CO", fullName: "Colombian Peso" },
  CRC: { countryCode: "CR", fullName: "Costa Rican Colón" },
  CUP: { countryCode: "CU", fullName: "Cuban Peso" },
  CVE: { countryCode: "CV", fullName: "Cape Verdean Escudo" },
  CYP: { countryCode: "CY", fullName: "Cypriot Pound" },
  CZK: { countryCode: "CZ", fullName: "Czech Koruna" },
  DJF: { countryCode: "DJ", fullName: "Djiboutian Franc" },
  DKK: { countryCode: "DK", fullName: "Danish Krone" },
  DOP: { countryCode: "DO", fullName: "Dominican Peso" },
  DZD: { countryCode: "DZ", fullName: "Algerian Dinar" },
  ECS: { countryCode: "EC", fullName: "Ecuadorian Sucre" },
  EEK: { countryCode: "EE", fullName: "Estonian Kroon" },
  EGP: { countryCode: "EG", fullName: "Egyptian Pound" },
  ETB: { countryCode: "ET", fullName: "Ethiopian Birr" },
  EUR: { countryCode: "FR", fullName: "Euro" },
  FJD: { countryCode: "FJ", fullName: "Fijian Dollar" },
  FKP: { countryCode: "FK", fullName: "Falkland Islands Pound" },
  GBP: { countryCode: "GB", fullName: "British Pound Sterling" },
  GEL: { countryCode: "GE", fullName: "Georgian Lari" },
  GGP: { countryCode: "GG", fullName: "Guernsey Pound" },
  GHS: { countryCode: "GH", fullName: "Ghanaian Cedi" },
  GIP: { countryCode: "GI", fullName: "Gibraltar Pound" },
  GMD: { countryCode: "GM", fullName: "Gambian Dalasi" },
  GNF: { countryCode: "GN", fullName: "Guinean Franc" },
  GTQ: { countryCode: "GT", fullName: "Guatemalan Quetzal" },
  GYD: { countryCode: "GY", fullName: "Guyanese Dollar" },
  HKD: { countryCode: "HK", fullName: "Hong Kong Dollar" },
  HNL: { countryCode: "HN", fullName: "Honduran Lempira" },
  HRK: { countryCode: "HR", fullName: "Croatian Kuna" },
  HTG: { countryCode: "HT", fullName: "Haitian Gourde" },
  HUF: { countryCode: "HU", fullName: "Hungarian Forint" },
  IDR: { countryCode: "ID", fullName: "Indonesian Rupiah" },
  ILS: { countryCode: "IL", fullName: "Israeli New Shekel" },
  INR: { countryCode: "IN", fullName: "Indian Rupee" },
  IQD: { countryCode: "IQ", fullName: "Iraqi Dinar" },
  IRR: { countryCode: "IR", fullName: "Iranian Rial" },
  ISK: { countryCode: "IS", fullName: "Icelandic Króna" },
  JMD: { countryCode: "JM", fullName: "Jamaican Dollar" },
  JOD: { countryCode: "JO", fullName: "Jordanian Dinar" },
  JPY: { countryCode: "JP", fullName: "Japanese Yen" },
  KES: { countryCode: "KE", fullName: "Kenyan Shilling" },
  KGS: { countryCode: "KG", fullName: "Kyrgyzstani Som" },
  KHR: { countryCode: "KH", fullName: "Cambodian Riel" },
  KMF: { countryCode: "KM", fullName: "Comorian Franc" },
  KPW: { countryCode: "KP", fullName: "North Korean Won" },
  KRW: { countryCode: "KR", fullName: "South Korean Won" },
  KWD: { countryCode: "KW", fullName: "Kuwaiti Dinar" },
  KYD: { countryCode: "KY", fullName: "Cayman Islands Dollar" },
  KZT: { countryCode: "KZ", fullName: "Kazakhstani Tenge" },
  LAK: { countryCode: "LA", fullName: "Lao Kip" },
  LBP: { countryCode: "LB", fullName: "Lebanese Pound" },
  LKR: { countryCode: "LK", fullName: "Sri Lankan Rupee" },
  LRD: { countryCode: "LR", fullName: "Liberian Dollar" },
  LSL: { countryCode: "LS", fullName: "Lesotho Loti" },
  LTL: { countryCode: "LT", fullName: "Lithuanian Litas" },
  LVL: { countryCode: "LV", fullName: "Latvian Lats" },
  LYD: { countryCode: "LY", fullName: "Libyan Dinar" },
  MAD: { countryCode: "MA", fullName: "Moroccan Dirham" },
  MDL: { countryCode: "MD", fullName: "Moldovan Leu" },
  MGA: { countryCode: "MG", fullName: "Malagasy Ariary" },
  MKD: { countryCode: "MK", fullName: "Macedonian Denar" },
  MMK: { countryCode: "MM", fullName: "Myanma Kyat" },
  MNT: { countryCode: "MN", fullName: "Mongolian Tögrög" },
  MOP: { countryCode: "MO", fullName: "Macanese Pataca" },
  MRU: { countryCode: "MR", fullName: "Mauritanian Ouguiya" },
  MUR: { countryCode: "MU", fullName: "Mauritian Rupee" },
  MVR: { countryCode: "MV", fullName: "Maldivian Rufiyaa" },
  MWK: { countryCode: "MW", fullName: "Malawian Kwacha" },
  MXN: { countryCode: "MX", fullName: "Mexican Peso" },
  MYR: { countryCode: "MY", fullName: "Malaysian Ringgit" },
  MZN: { countryCode: "MZ", fullName: "Mozambican Metical" },
  NAD: { countryCode: "NA", fullName: "Namibian Dollar" },
  NGN: { countryCode: "NG", fullName: "Nigerian Naira" },
  NOK: { countryCode: "NO", fullName: "Norwegian Krone" },
  NPR: { countryCode: "NP", fullName: "Nepalese Rupee" },
  NZD: { countryCode: "NZ", fullName: "New Zealand Dollar" },
  OMR: { countryCode: "OM", fullName: "Omani Rial" },
  PAB: { countryCode: "PA", fullName: "Panamanian Balboa" },
  PEN: { countryCode: "PE", fullName: "Peruvian Sol" },
  PGK: { countryCode: "PG", fullName: "Papua New Guinean Kina" },
  PHP: { countryCode: "PH", fullName: "Philippine Peso" },
  PKR: { countryCode: "PK", fullName: "Pakistani Rupee" },
  PLN: { countryCode: "PL", fullName: "Polish Zloty" },
  PYG: { countryCode: "PY", fullName: "Paraguayan Guarani" },
  QAR: { countryCode: "QA", fullName: "Qatari Rial" },
  RON: { countryCode: "RO", fullName: "Romanian Leu" },
  RSD: { countryCode: "RS", fullName: "Serbian Dinar" },
  RUB: { countryCode: "RU", fullName: "Russian Ruble" },
  RWF: { countryCode: "RW", fullName: "Rwandan Franc" },
  SAR: { countryCode: "SA", fullName: "Saudi Riyal" },
  SBD: { countryCode: "SB", fullName: "Solomon Islands Dollar" },
  SCR: { countryCode: "SC", fullName: "Seychellois Rupee" },
  SDG: { countryCode: "SD", fullName: "Sudanese Pound" },
  SEK: { countryCode: "SE", fullName: "Swedish Krona" },
  SGD: { countryCode: "SG", fullName: "Singapore Dollar" },
  SHP: { countryCode: "SH", fullName: "Saint Helena Pound" },
  SLL: { countryCode: "SL", fullName: "Sierra Leonean Leone" },
  SOS: { countryCode: "SO", fullName: "Somali Shilling" },
  SRD: { countryCode: "SR", fullName: "Surinamese Dollar" },
  SSP: { countryCode: "SS", fullName: "South Sudanese Pound" },
  STN: { countryCode: "ST", fullName: "São Tomé and Príncipe Dobra" },
  SVC: { countryCode: "SV", fullName: "Salvadoran Colón" },
  SYP: { countryCode: "SY", fullName: "Syrian Pound" },
  SZL: { countryCode: "SZ", fullName: "Swazi Lilangeni" },
  THB: { countryCode: "TH", fullName: "Thai Baht" },
  TJS: { countryCode: "TJ", fullName: "Tajikistani Somoni" },
  TMT: { countryCode: "TM", fullName: "Turkmenistani Manat" },
  TND: { countryCode: "TN", fullName: "Tunisian Dinar" },
  TOP: { countryCode: "TO", fullName: "Tongan Paʻanga" },
  TRY: { countryCode: "TR", fullName: "Turkish Lira" },
  TTD: { countryCode: "TT", fullName: "Trinidad and Tobago Dollar" },
  TWD: { countryCode: "TW", fullName: "New Taiwan Dollar" },
  TZS: { countryCode: "TZ", fullName: "Tanzanian Shilling" },
  UAH: { countryCode: "UA", fullName: "Ukrainian Hryvnia" },
  UGX: { countryCode: "UG", fullName: "Ugandan Shilling" },
  USD: { countryCode: "US", fullName: "United States Dollar" },
  UYU: { countryCode: "UY", fullName: "Uruguayan Peso" },
  UZS: { countryCode: "UZ", fullName: "Uzbekistani Som" },
  VES: { countryCode: "VE", fullName: "Venezuelan Bolívar Soberano" },
  VND: { countryCode: "VN", fullName: "Vietnamese Dong" },
  VUV: { countryCode: "VU", fullName: "Vanuatu Vatu" },
  WST: { countryCode: "WS", fullName: "Samoan Tala" },
  XAF: { countryCode: "XA", fullName: "CFA Franc BEAC" },
  XCD: { countryCode: "XC", fullName: "East Caribbean Dollar" },
  YER: { countryCode: "YE", fullName: "Yemeni Rial" },
  ZAR: { countryCode: "ZA", fullName: "South African Rand" },
  ZMK: { countryCode: "ZM", fullName: "Zambian Kwacha" },
  ZWD: { countryCode: "ZW", fullName: "Zimbabwean Dollar" },
};
